---
- name: Install nginx on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: "Update apt cache"
      apt:
        update_cache: yes
    - name: "Install Nginx"
      package:
        name: "nginx"
        state: present
    - name: "Start Nginx"
      service:
        name: nginx
        state: started
        enabled: yes

