name: Upload index.html

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Upload index.html
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem

          # Replace USERNAME, HOSTNAME, and REMOTE_PATH with your server's details
          yes | scp -i ssh_key.pem index.html ubuntu@ec2-3-68-167-151.eu-central-1.compute.amazonaws.com:/home/ubuntu
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
